source 'https://rubygems.org'

gem 'bcrypt'
gem 'extra_print'
# PostgreSQL driver
gem 'pg'

# Sinatra driver
gem 'sinatra', '~> 1.0'
gem 'sinatra-contrib'

gem 'activerecord', '~>5.1.0'
gem 'activesupport', '~>5.1.0'

gem 'rake'

gem 'shotgun', '~>0.9.1'

group :test do
  gem 'capybara'
  gem 'rack-test'
  gem 'rspec', '~>3.0'
  gem 'shoulda-matchers'
end

group :test, :development do
  gem 'factory_girl'
  gem 'faker'
end
